<?php require dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '_noncename.phtml'; ?>

<?php $description = esc_html( $this->description ); ?>

<?php if( $description <> '' ) : ?>
  <p style="margin-bottom:5px;">
    <?php echo $description; ?>
  </p>
<?php endif;?>

<input style="width: 100px; height: 50px;" type="color" name="<?php echo $this->id ?>" value="<?php echo $this->getValue( $this->id ) ?>" />