<?php require dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '_noncename.phtml'; ?>

<?php $description = esc_html( $this->description ); ?>
<?php $values      = $this->getValue( $this->id ); ?>

<?php if( !is_array( $values ) ) $values   = []; ?>
<?php if( count( $values ) < 1 ) $values[] = [ '', '' ]; ?>

<div id="repeater-<?= $this->id ?>">
  <table style="margin-top:10px;width:100%;" class="repeater-content-wrapper-collection">
    <?php if( $description <> '' ) : ?>
      <tr>
        <td colspan="3">
          <p style="margin: 0 0 7px 0;">
            <?= $description; ?>
          </p>
        </td>
      </tr>
    <?php endif;?>

    <?php $i = 0; foreach( $values as $value ) : ?>
      <tr class="repeater-content-wrapper">
        <td>
          <div style="margin-right:5px;margin-bottom:10px;">
            <input type="text" name="<?= $this->id ?>[<?= $i ?>][0]" value="<?= esc_attr($value[0]) ?>" class="widefat" />
          </div>
        </td>

        <td>
          <div style="margin-left:5px;margin-right:5px;margin-bottom:10px;">
            <input type="text" name="<?= $this->id ?>[<?= $i ?>][1]" value="<?= esc_attr($value[1]) ?>" class="widefat" />
          </div>
        </td>

        <td style="width:1px;">
          <input style="margin-bottom:10px;" class="repeater-button-remove button" type="button" value="–" />
        </td>
      </tr>
    <?php $i++; endforeach;?>

    <tr class="repeater-add-wrapper">
      <td colspan="2"></td>
      <td style="width:1px;">
        <input style="float:right;" id="repeater-<?= $this->id ?>-button-add" type="button" class="button-primary" value="+" />
      </td>
    </tr>
  </table>
</div>

<script type="text/javascript">
  ( function( $ )
  {
    $( '#repeater-<?= $this->id ?> .repeater-button-remove' )
      .click(
        function()
        {
          $( this ).parent().parent().remove();
        });

    var
    i          = <?= $i ?>,
    collection = $( '#repeater-<?= $this->id ?> .repeater-content-wrapper-collection' ),
    addTr      = $( '.repeater-add-wrapper', collection ),
    wrapper    = $( '.repeater-content-wrapper', collection ).first().clone( true );

    $( 'input.widefat', wrapper ).removeAttr( 'value' );

    $( '#repeater-<?= $this->id ?>-button-add' )
      .click(
        function()
        {
          i++;

          var clone = wrapper.clone( true );

          $( 'input.widefat', clone ).each(
            function( n, input )
            {
              $( input ).attr( 'name', '<?= $this->id ?>[' + i + '][' + n + ']' );
            });

          addTr.before( clone );
        });
  })( jQuery );
</script>