<?php require dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '_noncename.phtml'; ?>

<?php $description = esc_html( $this->description ); ?>
<?php $values      = $this->getValue( $this->id ); ?>

<?php if( !is_array( $values ) ) $values   = array(); ?>
<?php if( count( $values ) < 1 ) $values[] = ''; ?>

<div id="repeater-<?php echo $this->id ?>">
  <table style="margin-top:10px;width:100%;" class="repeater-content-wrapper-collection">
    <?php if( $description <> '' ) : ?>
      <tr>
        <td colspan="2">
          <p style="margin: 0 0 7px 0;">
            <?php echo $description; ?>
          </p>
        </td>
      </tr>
    <?php endif;?>

    <?php foreach( $values as $value ) : ?>
      <tr class="repeater-content-wrapper">
        <td>
          <div style="margin-right:5px;margin-bottom:10px;">
            <input type="text" name="<?php echo $this->id ?>[]" value="<?php echo esc_attr($value) ?>" class="widefat" />
          </div>
        </td>

        <td style="width:1px;">
          <input style="margin-bottom:10px;" class="repeater-button-remove button" type="button" value="–" />
        </td>
      </tr>
    <?php endforeach;?>

    <tr class="repeater-add-wrapper">
      <td></td>
      <td style="width:1px;">
        <input style="float:right;" id="repeater-<?php echo $this->id ?>-button-add" type="button" class="button-primary" value="+" />
      </td>
    </tr>
  </table>
</div>

<script type="text/javascript">
  ( function( $ )
  {
    $( '#repeater-<?php echo $this->id ?> .repeater-button-remove' )
      .click(
        function()
        {
          $( this ).parent().parent().remove();
        });

    var
    collection = $( '#repeater-<?php echo $this->id ?> .repeater-content-wrapper-collection' ),
    addTr      = $( '.repeater-add-wrapper', collection ),
    wrapper    = $( '.repeater-content-wrapper', collection ).first().clone( true );

    $( 'input.widefat', wrapper ).removeAttr( 'value' );

    $( '#repeater-<?php echo $this->id ?>-button-add' )
      .click(
        function()
        {
          addTr.before( wrapper.clone( true ) );
        });
  })( jQuery );
</script>