<?php $description = esc_html( $this->description ); ?>
<?php $values      = $this->getValue( $this->id ); ?>

<?php if( !is_array( $values ) ) $values   = []; ?>
<?php if( count( $values ) < 1 ) $values[] = ''; ?>

<?php if($description) : ?>
  <h3><?= $description ?></h3>
<?php endif ?>

<?php foreach( $values as $value ) : if( !$value ) continue ?>
  <?php if(is_array($value)): ?>
    <table class="widefat fixed" cellspacing="0" style="border:0px; margin-bottom: 25px;">
      <?php foreach($value as $key => $innerVal) : ?>
        <tr>
          <td style="border-bottom:1px solid #eee"><?= $key ?></td>
          <td style="border-bottom:1px solid #eee"><?= nl2br( $innerVal ) ?></td>
        </tr>
      <?php endforeach ?>
    </table>
  <?php else: ?>
    <?php if($i++ > 0) : ?>
      <hr />
    <?php endif ?>

    <p><?= nl2br( $value ) ?></p>
  <?php endif ?>
  <?php //print_r($value ); ?>
<?php endforeach ?>