<?php require dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '_noncename.phtml'; ?>

<?php $description = esc_html( $this->description ); ?>

<?php if( $description <> '' ) : ?>
  <p style="margin-bottom:5px;">
    <?php echo $description; ?>
  </p>
<?php endif;?>

<input style="font-size:1.7em;" type="text" name="<?php echo $this->id ?>" value="<?php echo esc_attr($this->getValue( $this->id )) ?>" class="widefat" />