<?php require dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '_noncename.phtml'; ?>

<?php $description = esc_html( $this->description ); ?>

<?php if( $description <> '' ) : ?>
  <p style="margin-bottom:5px;">
    <?php echo $description; ?>
  </p>
<?php endif;?>


<div id="dubbel-image-<?php echo $this->id ?>">
  <table style="margin-top:10px;width:100%;" class="content-wrapper-collection">
    <tr class="content-wrapper">
      <td style="position: relative;">
        <input placeholder="Youtube" type="text" name="<?php echo $this->id ?>[0]" value="<?php echo $this->getValue($this->id)[0] ?>" class="widefat" />
      </td>

      <td style="position: relative;">
        <input placeholder="Bild" type="text" name="<?php echo $this->id ?>[1]" value="<?php echo $this->getValue($this->id)[1] ?>" class="widefat" />
      </td>
    </tr>
  </table>
</div>