<?php require dirname( __FILE__ ) . DIRECTORY_SEPARATOR . '_noncename.phtml'; ?>

<?php $description = esc_html( $this->description ); ?>

<?php if( $description <> '' ) : ?>
  <p style="margin-bottom:5px;">
    <?= $description; ?>
  </p>
<?php endif;?>


<div id="dubbel-image-<?= $this->id ?>">
  <table style="margin-top:10px;width:100%;" class="content-wrapper-collection">
    <tr class="content-wrapper">
      <td style="position: relative;">
        <input placeholder="Youtube" type="text" name="<?= $this->id ?>[0]" value="<?= esc_attr($this->getValue($this->id)[0]) ?>" class="widefat" />
      </td>

      <td style="position: relative;">
        <input placeholder="Bild" type="text" name="<?= $this->id ?>[1]" value="<?= esc_attr($this->getValue($this->id)[1]) ?>" class="widefat" />
      </td>
    </tr>
  </table>
</div>